import { chromium } from 'playwright'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

const browser=await chromium.launch({channel:'msedge',headless:true})
process.on('uncaughtException',async error=>{console.error(error);await browser.close();process.exit(1)})
process.on('unhandledRejection',async error=>{console.error(error);await browser.close();process.exit(1)})
const context=await browser.newContext({viewport:{width:1584,height:992}})
const page=await context.newPage(),errors=[]
page.setDefaultTimeout(10000)
page.on('console',message=>{if(message.type()==='error')errors.push(message.text())})
page.on('pageerror',error=>errors.push(error.message))
await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'})
const canvas=page.locator('.document-canvas'),box=await canvas.boundingBox()
if(!box)throw new Error('Canvas not found')
await page.mouse.move(box.x+box.width+30,box.y+20)
await page.mouse.down()
await page.mouse.move(box.x+4,box.y+box.height-4,{steps:12})
await page.mouse.up()
const selected=page.locator('.document-canvas .canvas-element.selected'),selectedCount=await selected.count()
if(selectedCount<2)throw new Error(`Marquee selected only ${selectedCount} elements`)
const before=await page.locator('.document-canvas .canvas-element').evaluateAll(nodes=>nodes.map(node=>Number.parseFloat(getComputedStyle(node).top)))
const firstBox=await selected.first().boundingBox()
if(!firstBox)throw new Error('Selected element not found')
await page.mouse.move(firstBox.x+firstBox.width/2,firstBox.y+firstBox.height/2)
await page.mouse.down()
await page.mouse.move(firstBox.x+firstBox.width/2,firstBox.y+firstBox.height/2+30,{steps:8})
await page.mouse.up()
const afterDrag=await page.locator('.document-canvas .canvas-element').evaluateAll(nodes=>nodes.map(node=>Number.parseFloat(getComputedStyle(node).top)))
const deltas=afterDrag.map((value,index)=>Math.round(value-before[index]))
if(!deltas.every(delta=>delta===40))throw new Error(`Elements did not move together: ${deltas.join(',')}`)
await page.keyboard.press('Shift+ArrowDown')
const afterKey=await page.locator('.document-canvas .canvas-element').evaluateAll(nodes=>nodes.map(node=>Number.parseFloat(getComputedStyle(node).top)))
if(!afterKey.every((value,index)=>value-afterDrag[index]===10))throw new Error('Shift+ArrowDown did not move all elements by 10px')
const screenshot=join(tmpdir(),'canvasnote-multiselect.png')
await page.screenshot({path:screenshot,fullPage:true})
console.log(JSON.stringify({selectedCount,dragDeltas:deltas,keyDelta:10,errors,screenshot},null,2))
await browser.close()
