import {useRef,useState,type PointerEvent as PE} from 'react'
import type {EditorElement,EditorPage} from '../types'
import {bounds,inside,selectionForElement} from './operations'
type Props={page:EditorPage;zoom:number;selected:string[];editing:string|null;onSelected:(ids:string[])=>void;onEditing:(id:string|null)=>void;onElements:(els:EditorElement[],commit?:boolean)=>void;nodeRef:(n:HTMLDivElement|null)=>void}
export function EditorCanvas({page,zoom,selected,editing,onSelected,onEditing,onElements,nodeRef}:Props){
 const node=useRef<HTMLDivElement|null>(null),drag=useRef<any>(null),mark=useRef<any>(null),[box,setBox]=useState<any>(null)
 const point=(e:PE)=>{const r=node.current!.getBoundingClientRect();return{x:(e.clientX-r.left)/zoom,y:(e.clientY-r.top)/zoom}}
 const downCanvas=(e:PE)=>{if((e.target as HTMLElement).closest('.canvas-element'))return;e.preventDefault();(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);const p=point(e),m={sx:p.x,sy:p.y,x:p.x,y:p.y,width:0,height:0};mark.current=m;setBox(m);onEditing(null)}
 const moveCanvas=(e:PE)=>{if(!mark.current)return;const p=point(e),m={...mark.current,x:Math.min(mark.current.sx,p.x),y:Math.min(mark.current.sy,p.y),width:Math.abs(p.x-mark.current.sx),height:Math.abs(p.y-mark.current.sy)};mark.current=m;setBox(m)}
 const upCanvas=()=>{if(!mark.current)return;const m=mark.current;onSelected(m.width<3&&m.height<3?[]:inside(page.elements,m));mark.current=null;setBox(null)}
 const down=(e:PE,el:EditorElement,mode:'move'|'resize')=>{if(el.locked||editing===el.id)return;e.preventDefault();e.stopPropagation();(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);const ids=selectionForElement(page.elements,el,selected,e.shiftKey);onSelected(ids);drag.current={id:el.id,ids,x:e.clientX,y:e.clientY,mode,w:el.width,h:el.height,latest:page.elements,start:Object.fromEntries(page.elements.filter(x=>ids.includes(x.id)).map(x=>[x.id,{x:x.x,y:x.y}]))}}
 const move=(e:PE)=>{const d=drag.current;if(!d)return;e.preventDefault();const dx=(e.clientX-d.x)/zoom,dy=(e.clientY-d.y)/zoom;const next=d.mode==='resize'?page.elements.map(x=>x.id===d.id?{...x,width:Math.max(24,Math.round(d.w+dx)),height:Math.max(24,Math.round(d.h+dy))}:x):page.elements.map(x=>d.ids.includes(x.id)?{...x,x:Math.round(d.start[x.id].x+dx),y:Math.round(d.start[x.id].y+dy)}:x);d.latest=next;onElements(next)}
 const up=()=>{const d=drag.current;if(!d)return;drag.current=null;onElements(d.latest,true)};const group=bounds(page.elements,selected)
 return <div className="canvas-stage-v2" onPointerDown={downCanvas} onPointerMove={moveCanvas} onPointerUp={upCanvas} onPointerCancel={upCanvas}><div className="canvas-wrap-v2" style={{width:`calc(var(--page-width) * ${zoom})`,height:`calc(var(--page-height) * ${zoom})`}}><div className="canvas-zoom-v2" style={{transform:`scale(${zoom})`}}><div className="document-canvas" ref={n=>{node.current=n;nodeRef(n)}} style={{background:page.background}}>
 {page.elements.slice().sort((a,b)=>a.zIndex-b.zIndex).map(el=><div key={el.id} className={`canvas-element ${selected.includes(el.id)?'selected':''} ${editing===el.id?'editing':''} ${el.locked?'locked':''}`} style={{left:el.x,top:el.y,width:el.width,height:el.height,transform:`rotate(${el.rotation}deg)`,zIndex:el.zIndex,backgroundColor:el.style.backgroundColor,border:`${el.style.borderWidth||0}px solid ${el.style.borderColor||'transparent'}`,borderRadius:el.style.borderRadius,clipPath:el.style.clipPath,opacity:el.style.opacity??1}} onPointerDown={e=>down(e,el,'move')} onPointerMove={move} onPointerUp={up} onDoubleClick={()=>el.type==='text'&&onEditing(el.id)}>
 {el.type==='image'?<img src={el.src}/>:el.type==='text'?<div className="text-content" contentEditable={editing===el.id} suppressContentEditableWarning style={{fontFamily:el.style.fontFamily,fontSize:el.style.fontSize,fontWeight:el.style.fontWeight,fontStyle:el.style.fontStyle,textAlign:el.style.textAlign,color:el.style.color}} onBlur={e=>{onElements(page.elements.map(x=>x.id===el.id?{...x,content:e.currentTarget.innerText}:x),true);onEditing(null)}}>{el.content}</div>:null}
 {selected.includes(el.id)&&!el.locked&&<span className="selection-outline"/>}{selected.length===1&&selected[0]===el.id&&!el.locked&&<button className="resize-handle se" aria-label="サイズ変更" onPointerDown={e=>down(e,el,'resize')} onPointerMove={move} onPointerUp={up}/>}</div>)}
 {selected.length>1&&group&&<div className="group-outline" style={{left:group.x,top:group.y,width:group.width,height:group.height}}/>}{box&&<div className="selection-marquee" style={{left:box.x,top:box.y,width:box.width,height:box.height}}/>}
 </div></div></div></div>
}
