import type {EditorElement} from '../types'
export const inside=(els:EditorElement[],b:{x:number;y:number;width:number;height:number})=>els.filter(e=>!e.locked&&e.x<b.x+b.width&&e.x+e.width>b.x&&e.y<b.y+b.height&&e.y+e.height>b.y).map(e=>e.id)
export const bounds=(els:EditorElement[],ids:string[])=>{const s=els.filter(e=>ids.includes(e.id));if(!s.length)return null;const x=Math.min(...s.map(e=>e.x)),y=Math.min(...s.map(e=>e.y)),r=Math.max(...s.map(e=>e.x+e.width)),b=Math.max(...s.map(e=>e.y+e.height));return{x,y,width:r-x,height:b-y}}
export function align(els:EditorElement[],ids:string[],m:'left'|'center'|'right'|'top'|'middle'|'bottom'){const b=bounds(els,ids);if(!b)return els;return els.map(e=>{if(!ids.includes(e.id))return e;let{x,y}=e;if(m==='left')x=b.x;if(m==='center')x=b.x+(b.width-e.width)/2;if(m==='right')x=b.x+b.width-e.width;if(m==='top')y=b.y;if(m==='middle')y=b.y+(b.height-e.height)/2;if(m==='bottom')y=b.y+b.height-e.height;return{...e,x:Math.round(x),y:Math.round(y)}})}
export function distribute(els:EditorElement[],ids:string[],axis:'x'|'y'){const s=els.filter(e=>ids.includes(e.id)).sort((a,b)=>a[axis]-b[axis]);if(s.length<3)return els;const first=s[0][axis],last=s.at(-1)![axis]+(axis==='x'?s.at(-1)!.width:s.at(-1)!.height),used=s.reduce((n,e)=>n+(axis==='x'?e.width:e.height),0),gap=(last-first-used)/(s.length-1),u=new Map<string,number>();let c=first;for(const e of s){u.set(e.id,c);c+=(axis==='x'?e.width:e.height)+gap}return els.map(e=>u.has(e.id)?{...e,[axis]:Math.round(u.get(e.id)!)}:e)}
export const isPdfBackground=(e:EditorElement)=>e.type==='image'&&e.locked===true&&e.pdfSource?.kind==='image'
export const setPdfBackgroundVisible=(els:EditorElement[],visible:boolean)=>els.map(e=>isPdfBackground(e)?{...e,style:{...e.style,opacity:visible?1:0}}:e)
export const removePdfBackground=(els:EditorElement[])=>els.filter(e=>!isPdfBackground(e))
export const groupElements=(els:EditorElement[],ids:string[],groupId:string)=>els.map(e=>ids.includes(e.id)?{...e,groupId}:e)
export const selectionForElement=(els:EditorElement[],el:EditorElement,selected:string[],additive=false)=>{const grouped=el.groupId?els.filter(x=>x.groupId===el.groupId&&!x.locked).map(x=>x.id):[el.id];return selected.includes(el.id)?selected:additive?[...new Set([...selected,...grouped])]:grouped}
