import { useRef, useState } from 'react'
import { FileCode2, FileJson, FileUp, MonitorDown, Server } from 'lucide-react'

export function ImportDialog({onClose,onImportHtml,onImportProject}:{onClose:()=>void;onImportHtml:(html:string)=>void|Promise<void>;onImportProject:(json:string)=>void}){
 const [html,setHtml]=useState(''),[loading,setLoading]=useState(false),[message,setMessage]=useState(''); const file=useRef<HTMLInputElement>(null)
 const read=(f:File)=>{const reader=new FileReader();reader.onload=()=>{const text=String(reader.result);if(f.name.endsWith('.json'))onImportProject(text);else{setHtml(text)}};reader.readAsText(f)}
 return <div className="dialog-backdrop" onMouseDown={loading?undefined:onClose}><div className="dialog" onMouseDown={e=>e.stopPropagation()}><h2>HTMLを読み込む</h2><p>通常のHTML/CSSをブラウザで描画し、文字・画像・装飾を編集可能な要素へ変換します。</p><textarea value={html} onChange={e=>setHtml(e.target.value)} placeholder="HTMLをここに貼り付け…" autoFocus disabled={loading}/>{message&&<div className="error-box">{message}</div>}<div className="dialog-actions"><input ref={file} hidden type="file" accept=".html,.htm,.json,text/html,application/json" onChange={e=>e.target.files?.[0]&&read(e.target.files[0])}/><button onClick={()=>file.current?.click()} disabled={loading}><FileUp/>ファイルを選択</button><span className="spacer"/><button onClick={onClose} disabled={loading}>キャンセル</button><button className="primary-button" disabled={!html.trim()||loading} onClick={async()=>{setLoading(true);setMessage('');try{await onImportHtml(html)}catch(e){setMessage(e instanceof Error?e.message:'HTMLを読み込めませんでした。')}finally{setLoading(false)}}}><FileCode2/>{loading?'変換中…':'読み込む'}</button></div></div></div>
}

export function ProjectDialog({onClose,onJson,onHtml,onLoad}:{onClose:()=>void;onJson:()=>void;onHtml:()=>void;onLoad:()=>void}){return <div className="dialog-backdrop" onMouseDown={onClose}><div className="dialog compact" onMouseDown={e=>e.stopPropagation()}><h2>プロジェクト</h2><div className="option-list"><button onClick={onJson}><FileJson/><span><b>プロジェクトを保存</b><small>再編集できるJSONファイル</small></span></button><button onClick={onHtml}><FileCode2/><span><b>HTMLを書き出す</b><small>専用属性付きの単独HTML</small></span></button><button onClick={onLoad}><FileUp/><span><b>プロジェクトを開く</b><small>保存したJSONを読み込み</small></span></button></div></div></div>}

export function PdfDialog({onClose,onBrowser,onLocal,busy,progress,error}:{onClose:()=>void;onBrowser:()=>void;onLocal:()=>void;busy:boolean;progress:number;error:string}){return <div className="dialog-backdrop" onMouseDown={!busy?onClose:undefined}><div className="dialog compact" onMouseDown={e=>e.stopPropagation()}><h2>PDF出力</h2>{busy?<div className="progress-area"><div className="spinner"/><b>PDFを生成しています…</b><progress value={progress} max={1}/></div>:<div className="option-list"><button onClick={onBrowser}><MonitorDown/><span><b>すぐにPDF化</b><small>ブラウザ内で画像ベースのPDFを生成</small></span></button><button onClick={onLocal}><Server/><span><b>高品質PDF</b><small>localhost:4310 の印刷サーバーを使用</small></span></button></div>}{error&&<div className="error-box">{error}<code>npm run pdf-server</code></div>}</div></div>}
