import { AlignCenter, AlignLeft, AlignRight, BringToFront, Copy, SendToBack, Trash2 } from 'lucide-react'
import type { EditorElement } from '../types'

interface Props { element?:EditorElement;selectionCount:number;pageBackground:string;onChange:(patch:Partial<EditorElement>,commit?:boolean)=>void;onStyle:(patch:Partial<EditorElement['style']>,commit?:boolean)=>void;onDelete:()=>void;onDuplicate:()=>void;onLayer:(where:'front'|'back')=>void;onAlign:(where:'left'|'center'|'right'|'top'|'middle'|'bottom')=>void;onPageBackground:(color:string)=>void }
const Field=({label,value,onChange}:{label:string;value:number;onChange:(n:number)=>void})=><label className="number-field"><span>{label}</span><input type="number" value={Math.round(value)} onChange={e=>onChange(Number(e.target.value))}/></label>

export function Inspector(p:Props){const el=p.element;return <aside className="inspector">
  <div className="inspector-tabs"><button className="active">デザイン</button><button>レイヤー</button></div>
  {!el ? p.selectionCount>1?<div className="inspector-section multi-selection-panel"><h3>{p.selectionCount}個の要素を選択中</h3><p className="empty-hint">選択した要素のどれかをドラッグすると、まとめて移動できます。</p><div className="shortcut-guide"><span>↑ ↓ ← →</span><b>1px移動</b><span>Shift ＋ 矢印</span><b>10px移動</b></div><div className="danger-row"><button onClick={p.onDuplicate}><Copy/>まとめて複製</button><button onClick={p.onDelete}><Trash2/>まとめて削除</button></div></div>:<div className="inspector-section"><h3>ページ</h3><label className="color-row">背景色<input type="color" value={p.pageBackground} onChange={e=>p.onPageBackground(e.target.value)}/></label><p className="empty-hint">灰色の作業領域またはページの余白からドラッグすると、複数の要素を囲んで選択できます。</p></div> : <>
    <section className="inspector-section"><h3>位置とサイズ</h3><div className="field-grid"><Field label="X" value={el.x} onChange={x=>p.onChange({x},true)}/><Field label="Y" value={el.y} onChange={y=>p.onChange({y},true)}/><Field label="W" value={el.width} onChange={width=>p.onChange({width},true)}/><Field label="H" value={el.height} onChange={height=>p.onChange({height},true)}/></div><label className="range-row"><span>回転</span><input type="range" min="-180" max="180" value={el.rotation} onChange={e=>p.onChange({rotation:Number(e.target.value)})}/><output>{el.rotation}°</output></label></section>
    {el.type==='text'&&<section className="inspector-section"><h3>テキスト</h3><select className="wide-input" value={el.style.fontFamily} onChange={e=>p.onStyle({fontFamily:e.target.value},true)}><option>Noto Sans JP, sans-serif</option><option>Yu Gothic, sans-serif</option><option>Georgia, serif</option></select><div className="inline-controls"><input type="number" value={el.style.fontSize} onChange={e=>p.onStyle({fontSize:Number(e.target.value)},true)}/><button className={el.style.fontWeight===700?'active':''} onClick={()=>p.onStyle({fontWeight:el.style.fontWeight===700?400:700},true)}><b>B</b></button><button className={el.style.fontStyle==='italic'?'active':''} onClick={()=>p.onStyle({fontStyle:el.style.fontStyle==='italic'?'normal':'italic'},true)}><i>I</i></button></div><div className="segmented"><button className={el.style.textAlign==='left'?'active':''} onClick={()=>p.onStyle({textAlign:'left'},true)}><AlignLeft/></button><button className={el.style.textAlign==='center'?'active':''} onClick={()=>p.onStyle({textAlign:'center'},true)}><AlignCenter/></button><button className={el.style.textAlign==='right'?'active':''} onClick={()=>p.onStyle({textAlign:'right'},true)}><AlignRight/></button></div><label className="color-row">文字色<input type="color" value={el.style.color||'#182230'} onChange={e=>p.onStyle({color:e.target.value},true)}/></label></section>}
    <section className="inspector-section"><h3>塗りつぶしと枠線</h3><label className="color-row">塗りつぶし<input type="color" value={el.style.backgroundColor==='transparent'?'#ffffff':el.style.backgroundColor||'#ffffff'} onChange={e=>p.onStyle({backgroundColor:e.target.value},true)}/></label><label className="color-row">枠線<input type="color" value={el.style.borderColor==='transparent'?'#d8dee8':el.style.borderColor||'#d8dee8'} onChange={e=>p.onStyle({borderColor:e.target.value,borderWidth:el.style.borderWidth||1},true)}/></label><div className="field-grid"><Field label="太さ" value={el.style.borderWidth||0} onChange={borderWidth=>p.onStyle({borderWidth},true)}/><Field label="角丸" value={el.style.borderRadius||0} onChange={borderRadius=>p.onStyle({borderRadius},true)}/></div></section>
    <section className="inspector-section"><h3>整列</h3><div className="segmented six"><button onClick={()=>p.onAlign('left')}><AlignLeft/></button><button onClick={()=>p.onAlign('center')}><AlignCenter/></button><button onClick={()=>p.onAlign('right')}><AlignRight/></button><button onClick={()=>p.onLayer('front')} title="最前面"><BringToFront/></button><button onClick={()=>p.onLayer('back')} title="最背面"><SendToBack/></button></div><div className="danger-row"><button onClick={p.onDuplicate}><Copy/>複製</button><button onClick={p.onDelete}><Trash2/>削除</button></div></section>
  </>}
  </aside>}
