import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { MultiSelectCanvas } from './components/MultiSelectCanvas'
import { Inspector } from './components/Inspector'
import { ImportDialog, PdfDialog, ProjectDialog } from './components/Dialogs'
import { PageRail } from './components/PageRail'
import { Toolbar } from './components/Toolbar'
import { ExportPages } from './components/ExportPages'
import { Dashboard } from './components/Dashboard'
import { exportBrowserPdf, exportPagePng, download, projectToHtml } from './lib/exporter'
import { History } from './lib/history'
import { importRenderedHtml } from './lib/importer'
import { cloneElement, clonePage, createProject, createStarterPage, resizeProject, uid } from './lib/project'
import { deleteStoredProject, listProjects, loadProject, saveProject } from './lib/storage'
import { offsetSelected } from './lib/selection'
import type { CanvasProject, EditorElement, PagePreset } from './types'
import { PAGE_SIZES } from './types'

type Dialog = 'import'|'project'|'pdf'|null
const clone = <T,>(value:T):T => structuredClone(value)

export function App(){
 const initial=useMemo(()=>createProject(),[]); const history=useRef(new History(initial));
 const [project,setProjectState]=useState(initial),[projects,setProjects]=useState<CanvasProject[]>([]),[view,setView]=useState<'dashboard'|'editor'>('dashboard'),[pendingPng,setPendingPng]=useState(false),[pageIndex,setPageIndex]=useState(0),[selectedIds,setSelectedIds]=useState<string[]>([]),[editingId,setEditingId]=useState<string|null>(null),[zoom,setZoom]=useState(.75),[dialog,setDialog]=useState<Dialog>(null),[saving,setSaving]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('');
 const canvasNodes=useRef<Record<string,HTMLDivElement|null>>({}),saveTimer=useRef<number|undefined>(undefined);
 const page=project.pages[pageIndex]||project.pages[0],selected=selectedIds.length===1?page?.elements.find(e=>e.id===selectedIds[0]):undefined;
 const setProject=useCallback((next:CanvasProject,commit=true)=>{const value={...next,meta:{...next.meta,updatedAt:new Date().toISOString()}};if(commit)history.current.push(clone(value));setProjectState(value);setSaving(true);window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(async()=>{await saveProject(value);setProjects(await listProjects());setSaving(false)},500)},[])
 const mutate=(fn:(draft:CanvasProject)=>void,commit=true)=>{const next=clone(project);fn(next);setProject(next,commit)}

 useEffect(()=>{Promise.all([loadProject(),listProjects()]).then(([saved,items])=>{setProjects(items);if(saved?.version===1){history.current=new History(saved);setProjectState(saved)}})},[])
 useEffect(()=>{if(pendingPng&&view==='editor'){const timer=window.setTimeout(async()=>{const node=canvasNodes.current[project.pages[0].id];if(node)await exportPagePng(node,project.title);setPendingPng(false)},250);return()=>window.clearTimeout(timer)}},[pendingPng,view,project])
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).isContentEditable||['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement).tagName))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();const v=e.shiftKey?history.current.redo():history.current.undo();setProjectState(clone(v));return}if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();setProjectState(clone(history.current.redo()));return}if(mod&&e.key.toLowerCase()==='a'){e.preventDefault();setSelectedIds(page.elements.map(item=>item.id));return}if(mod&&e.key.toLowerCase()==='d'&&selectedIds.length){e.preventDefault();duplicateElement()}if((e.key==='Delete'||e.key==='Backspace')&&selectedIds.length){e.preventDefault();deleteElement()}if(selectedIds.length&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?10:1,dx=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,dy=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0;mutate(d=>{d.pages[pageIndex].elements=offsetSelected(d.pages[pageIndex].elements,selectedIds,dx,dy)})}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)})

 const updateElement=(id:string,patch:Partial<EditorElement>,commit=false)=>mutate(d=>{const el=d.pages[pageIndex].elements.find(x=>x.id===id);if(el)Object.assign(el,patch)},commit)
 const moveMany=(ids:string[],positions:Record<string,{x:number;y:number}>,commit=false)=>mutate(d=>{for(const el of d.pages[pageIndex].elements){const position=positions[el.id];if(ids.includes(el.id)&&position)Object.assign(el,position)}},commit)
 const selectElement=(id:string|null,additive=false)=>{if(!id){setSelectedIds([]);return}setSelectedIds(current=>additive?(current.includes(id)?current.filter(value=>value!==id):[...current,id]):current.includes(id)?current:[id])}
 const updateStyle=(patch:Partial<EditorElement['style']>,commit=false)=>{if(selected)updateElement(selected.id,{style:{...selected.style,...patch}},commit)}
 const addElement=(type:'text'|'shape'|'image',src?:string)=>{const max=Math.max(0,...page.elements.map(e=>e.zIndex));const el:EditorElement={id:uid(),type,x:120,y:120,width:type==='text'?460:260,height:type==='text'?90:180,rotation:0,zIndex:max+1,content:type==='text'?'新しいテキスト':undefined,src,style:{fontFamily:'Noto Sans JP, sans-serif',fontSize:36,fontWeight:600,color:'#182230',backgroundColor:type==='shape'?'#2764e7':'transparent',borderColor:'transparent',borderWidth:0,borderRadius:type==='shape'?12:0,textAlign:'left',opacity:1}};mutate(d=>d.pages[pageIndex].elements.push(el));setSelectedIds([el.id])}
 const deleteElement=()=>{if(!selectedIds.length)return;mutate(d=>{d.pages[pageIndex].elements=d.pages[pageIndex].elements.filter(e=>!selectedIds.includes(e.id))});setSelectedIds([])}
 const duplicateElement=()=>{if(!selectedIds.length)return;const copies=page.elements.filter(item=>selectedIds.includes(item.id)).map(cloneElement);mutate(d=>d.pages[pageIndex].elements.push(...copies));setSelectedIds(copies.map(item=>item.id))}
 const chooseImage=()=>{const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>addElement('image',String(reader.result));reader.readAsDataURL(f)};input.click()}
 const importProject=(raw:string)=>{try{const parsed=JSON.parse(raw) as CanvasProject;if(parsed.version!==1||!Array.isArray(parsed.pages))throw new Error();history.current=new History(parsed);setProjectState(parsed);setPageIndex(0);setDialog(null)}catch{setError('プロジェクトファイルを読み込めませんでした。')}}
 const openProjectFile=()=>{const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=()=>{const f=input.files?.[0];if(f)f.text().then(importProject)};input.click()}
 const doBrowserPdf=async()=>{setBusy(true);setError('');try{const nodes=project.pages.map(p=>canvasNodes.current[p.id]).filter(Boolean) as HTMLElement[];if(nodes.length!==project.pages.length)throw new Error('全ページを準備できませんでした。ページを一度選択してから再試行してください。');await exportBrowserPdf(nodes,project,setProgress);setDialog(null)}catch(e){setError(e instanceof Error?e.message:'PDF生成に失敗しました。')}finally{setBusy(false)}}
 const doLocalPdf=async()=>{setBusy(true);setError('');setProgress(.3);try{const res=await fetch('http://127.0.0.1:4310/api/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({html:projectToHtml(project)})});if(!res.ok)throw new Error(await res.text());setProgress(.9);const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${project.title}.pdf`;a.click();URL.revokeObjectURL(url);setDialog(null)}catch{setError('高品質PDFサーバーに接続できません。別のターミナルで次を実行してください。')}finally{setBusy(false)}}
 const size=PAGE_SIZES[project.preset]
 const openProject=(next:CanvasProject)=>{history.current=new History(next);setProjectState(next);setPageIndex(0);setSelectedIds([]);setView('editor')}
 const newProject=()=>{const next=createProject();saveProject(next).then(async()=>setProjects(await listProjects()));openProject(next)}
 const duplicateProject=(source:CanvasProject)=>{const now=new Date().toISOString(),next={...clone(source),id:uid(),title:`${source.title} のコピー`,meta:{createdAt:now,updatedAt:now}};saveProject(next).then(async()=>setProjects(await listProjects()))}
 const removeProject=async(source:CanvasProject)=>{await deleteStoredProject(source.id);setProjects(await listProjects())}
 if(view==='dashboard')return <Dashboard projects={projects} onNew={newProject} onOpen={openProject} onDuplicate={duplicateProject} onDelete={removeProject} onImage={source=>{openProject(source);setPendingPng(true)}} onImport={()=>{newProject();setDialog('import')}}/>
 return <div className="app-shell">
  <Toolbar title={project.title} preset={project.preset} zoom={zoom} saving={saving} canUndo={history.current.canUndo} canRedo={history.current.canRedo} onHome={()=>{listProjects().then(setProjects);setView('dashboard')}} onTitle={title=>mutate(d=>{d.title=title})} onPreset={preset=>{mutate(d=>resizeProject(d,preset));setZoom(preset.startsWith('Business')?1.5:preset.startsWith('A6')?1:.75)}} onZoom={setZoom} onUndo={()=>setProjectState(clone(history.current.undo()))} onRedo={()=>setProjectState(clone(history.current.redo()))} onAddText={()=>addElement('text')} onAddShape={()=>addElement('shape')} onImage={chooseImage} onImport={()=>setDialog('import')} onProject={()=>setDialog('project')} onPdf={()=>{setError('');setProgress(0);setDialog('pdf')}}/>
  <div className="editor-layout"><PageRail project={project} active={pageIndex} onSelect={i=>{setPageIndex(i);setSelectedIds([])}} onAdd={()=>{mutate(d=>d.pages.push(createStarterPage(d.pages.length)));setPageIndex(project.pages.length)}} onDuplicate={i=>{mutate(d=>d.pages.splice(i+1,0,clonePage(d.pages[i])));setPageIndex(i+1)}} onDelete={i=>{if(project.pages.length===1)return;mutate(d=>d.pages.splice(i,1));setPageIndex(Math.max(0,Math.min(pageIndex,project.pages.length-2)))}} onMove={(from,to)=>{if(from===to||Number.isNaN(from))return;mutate(d=>{const [p]=d.pages.splice(from,1);d.pages.splice(to,0,p)});setPageIndex(to)}}/>
   <main className="workspace" style={{'--page-width':`${size.width}px`,'--page-height':`${size.height}px`,'--zoom':zoom} as React.CSSProperties}><MultiSelectCanvas page={page} zoom={zoom} selectedIds={selectedIds} editingId={editingId} onSelect={selectElement} onSelectMany={setSelectedIds} onEditing={setEditingId} onChange={updateElement} onMoveMany={moveMany} canvasRef={node=>{canvasNodes.current[page.id]=node}}/></main>
   <Inspector element={selected} selectionCount={selectedIds.length} pageBackground={page.background} onChange={(patch,commit)=>selected&&updateElement(selected.id,patch,commit)} onStyle={updateStyle} onDelete={deleteElement} onDuplicate={duplicateElement} onLayer={where=>selected&&mutate(d=>{const els=d.pages[pageIndex].elements;selected.zIndex=where==='front'?Math.max(...els.map(e=>e.zIndex))+1:Math.min(...els.map(e=>e.zIndex))-1;const target=els.find(e=>e.id===selected.id);if(target)target.zIndex=selected.zIndex})} onAlign={where=>selected&&updateElement(selected.id,{x:where==='left'?0:where==='center'?(size.width-selected.width)/2:where==='right'?size.width-selected.width:selected.x,y:where==='top'?0:where==='middle'?(size.height-selected.height)/2:where==='bottom'?size.height-selected.height:selected.y},true)} onPageBackground={background=>mutate(d=>{d.pages[pageIndex].background=background})}/>
  </div><footer className="statusbar"><span>ページ <b>{pageIndex+1} / {project.pages.length}</b>{selectedIds.length>1&&<>　<b>{selectedIds.length}個を選択中</b></>}</span><span>ドラッグで囲む　 Shift + クリックで追加　矢印キーで移動　 Shift + 矢印で10px移動</span><span>{project.preset} · {Math.round(zoom*100)}%</span></footer>
  {dialog==='import'&&<ImportDialog onClose={()=>setDialog(null)} onImportHtml={async html=>{const imported=await importRenderedHtml(html);mutate(d=>{d.pages.splice(pageIndex,1,imported.page);d.preset=imported.preset;d.css=imported.css});setDialog(null);setSelectedIds([])}} onImportProject={importProject}/>} 
  {dialog==='project'&&<ProjectDialog onClose={()=>setDialog(null)} onJson={()=>download(`${project.title}.canvasnote.json`,JSON.stringify(project,null,2),'application/json')} onHtml={()=>download(`${project.title}.html`,projectToHtml(project),'text/html')} onLoad={openProjectFile}/>} 
  {dialog==='pdf'&&<PdfDialog onClose={()=>setDialog(null)} onBrowser={doBrowserPdf} onLocal={doLocalPdf} busy={busy} progress={progress} error={error}/>} 
  <ExportPages project={project} onNode={(id,node)=>{canvasNodes.current[id]=node}}/>
 </div>
}
